[theme]
primaryColor = "#F5B895"      # soft peach tone
backgroundColor = "#FFF4EC"   # very light peach for background
secondaryBackgroundColor = "#FFE0CC"   # deeper peach for sidebar and widgets
textColor = "#4F2C1D"         # dark brownish text for contrast
font = "sans serif"
