[theme]
primaryColor = "#A9A9A9"        # dark grey for buttons and accents
backgroundColor = "#F5F5F5"     # very light grey for the main background
secondaryBackgroundColor = "#D3D3D3"  # light grey for sidebar and widgets
textColor = "#333333"           # dark grey (almost black) for text
font = "sans serif"
